### PR TITLE
Fix misformatted fields in EIP-2515

### PR DESCRIPTION
**Pull request by lightclient**
Current output from `eip-validator`:

```console
Warning: EIPS/eip-2515.md        undefined method `requires (*optional)=' for #<EipValidator::Validator:0x0000557ce931cf48>
```

Additionally, it appears that the assigned EIP is incorrect as #2512 is unrelated.

### CODE REVIEW

**Comment by eip-automerger** [comment]
Hi! I'm a bot, and I wanted to automerge your PR, but couldn't because of the following issue(s):

 - EIP header in EIPS/eip-2515.md does not match: 2512
 - EIP 2515 requires approval from one of (@madeoftin)

**Comment by axic** [comment]
Reported these issues on #2605 and they were introduced in #2515.

**Comment by axic** [comment]
This fixes build/validation issues so I'm merging it.
